DROP TABLE IF EXISTS PROFESORES;
DROP TABLE IF EXISTS CURSOS;
 
CREATE TABLE PROFESORES (
  ID     INT          NOT NULL,
  NOMBRE VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID)
);
 
CREATE TABLE CURSOS (
  ID            INT          NOT NULL AUTO_INCREMENT,
  TITULO   		VARCHAR(254) NOT NULL,
  NIVEL			VARCHAR(20)  NOT NULL,
  HORAS		   	INT  		 NULL,
  ID_PROFESOR	INT  	     NOT NULL,
  ESTADO		INT(1)  	 NOT NULL,
  PRIMARY KEY (ID),
  foreign key (ID_PROFESOR) references PROFESORES(ID)
);
